ALTER TABLE "Store" ADD COLUMN "startingPoint" INTEGER NOT NULL DEFAULT 25000;
ALTER TABLE "Store" ADD COLUMN "returnPoint" INTEGER NOT NULL DEFAULT 30000;
ALTER TABLE "Store" ADD COLUMN "firstPlaceBonus" INTEGER NOT NULL DEFAULT 20;
ALTER TABLE "Store" ADD COLUMN "secondPlaceBonus" INTEGER NOT NULL DEFAULT 10;
ALTER TABLE "Store" ADD COLUMN "thirdPlaceBonus" INTEGER NOT NULL DEFAULT -10;
ALTER TABLE "Store" ADD COLUMN "fourthPlaceBonus" INTEGER NOT NULL DEFAULT -20;
